// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type File struct {
	ID           string `json:"id"`
	Filename     string `json:"filename"`
	Path         string `json:"path"`
	UploadedAt   string `json:"uploadedAt"`
	DownloadFile string `json:"downloadFile"`
	Size         int32  `json:"size"`
	User         *User  `json:"user"`
}

type Mutation struct {
}

type Query struct {
}

type StorageInfo struct {
	TotalFiles    int32  `json:"totalFiles"`
	TotalSize     int32  `json:"totalSize"`
	FormattedSize string `json:"formattedSize"`
}

type User struct {
	ID       string  `json:"id"`
	Name     *string `json:"name,omitempty"`
	Email    string  `json:"email"`
	Password string  `json:"password"`
}
